version: '3.9'

services:
  kepseefile:
    build: .
    ports:
      - 2020:3000
    environment:
      RUST_LOG: debug
      SECRET_KEY: "super_secret_token"
    volumes:
      - kepseefile-data:/files

volumes:
  kepseefile-data:
